services:
  postgres:
    image: docker.io/postgres:16
    container_name: dam-project-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dam
      POSTGRES_DB: dam-project
